name: Deployment

on: 
  workflow_dispatch:
  push: 
    brances:
      - main

env:
  APP_NAME: ${{ vars.APP_NAME }}
  APP_HOST: ${{ vars.APP_HOST }}

jobs:
  build:
    name: deployment
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: check linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: show the app name
        run : echo "app name $APP_NAME"

      - name: build golang app
        run: |
          GOOS=linux go build -o $APP_NAME -v
      
      - name: check executable
        run: ls

  deploy:
    needs: build     
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4 

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}  
          project_id: ${{ secrets.GCP_PROJECT_ID }}  
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/app1 . 

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/app1

      - name: Create or update instance template
        run: |
          gcloud compute instance-templates create go-app1-autoscale-cicd \
            --machine-type=1-standard-1 \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/app1 \
            --network=bab-lb-network \
            --subnet=lb-jakarta \
            --tags=lb-backend,allow-ssh
      
      - name: Update Managed Instance Group
        run: |
          gcloud compute instance-groups managed rolling-action start-update go-app1-autoscale-cicd \
            --version=template=go-app1-autoscale-cicd \
            --zone=asia-southeast2-a

  
    