name: Autoscale Artifact Registry

on: 
  workflow_dispatch:
  push: 
    brances:
      - main

env:
  APP_NAME: ${{ vars.APP_NAME }}
  APP_HOST: ${{ vars.APP_HOST }}

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: check linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: show the app name
        run : echo "app name $APP_NAME"

      - name: build golang app
        run: |
          GOOS=linux go build -o $APP_NAME -v
      
      - name: check executable
        run: ls

  deploy:
    needs: build     
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4 

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set the TAG value
        run: |
          CURRENT_DATE=$(date +%Y-%m-%d-%H-%M-%S)
          TAG="version-$CURRENT_DATE"
          TEMPLATE_NAME="go-app1-autoscale-cicd-$CURRENT_DATE"
          echo $TEMPLATE_NAME
          echo "TAG=$TAG" >> $GITHUB_ENV  # Set TAG as an environment variable
          echo "TEMPLATE_NAME=$TEMPLATE_NAME" >> $GITHUB_ENV  # Set TAG as an environment variable

      - name: Build Docker image
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/app1:$TAG .
      
      - name: Configure gcloud CLI
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Push Docker image to Artifact Registry
        run: |
          docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/app1:$TAG

      - name: Create instance template based on docker image
        run: |
          gcloud compute instance-templates create-with-container $TEMPLATE_NAME \
            --container-image=asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/app1:$TAG \
            --region=asia-southeast2 \
            --network-interface=network=bab-lb-network,subnet=lb-jakarta \
            --tags=allow-ssh,lb-backend \
            --machine-type=n1-standard-1 

      - name: Update managed instance group
        run: |
          gcloud compute instance-groups managed rolling-action start-update go-app1-group-autoscale-cicd-v3 \
            --version=template=$TEMPLATE_NAME \
            --max-unavailable=1 \
            --replacement-method=recreate \
            --region=asia-southeast2 