name: Deployment

on: 
  push: 
    brances:
      - main

jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: check linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: build golang app
        run: GOOS=linux go build -o app1 -v
      
      - name: check executable
        run: ls 

      - name: copy file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "app1"
          target: ./

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mv ./app1 /opt/golang/cicd
            systemctl stop app1.service
            systemctl start app1.service
            systemctl status app1.service


      
      

  
    